default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: ruff
        name: Fix using Ruff
        language: system
        types: [python]
        entry: poetry run ruff

      - id: black
        name: Format with Black
        language: system
        types: [python]
        entry: poetry run black

      - id: mypy
        name: Type check with Mypy
        language: system
        types: [python]
        entry: poetry run mypy
        args: [--show-error-codes, --pretty]

      - id: pytest
        name: Test with pytest
        language: system
        types: [python]
        pass_filenames: false
        entry: poetry run pytest
