- id: preferred-suffix
  name: Check filename has preferred suffix
  description: Check filenames to use single preferred suffix over other possible variants.
  language: python
  pass_filenames: true
  types: [file]
  entry: preferred-suffix

- id: alloy-format
  name: Format `.alloy` files
  description: Format `.alloy` files using `alloy fmt`. `alloy` must be installed.
  language: system
  files: \.alloy$
  entry: alloy fmt
  args: [--write]
