- id: check-directory-structure
  name: Check directory structure
  description: Check current directory structure.
  entry: check-directory-structure
  language: python
  pass_filenames: false
  types: [python]

- id: preferred-suffix
  name: Check filename has preferred suffix
  description: Check filenames to use single preferred suffix over other possible variants.
  entry: preferred-suffix
  language: python
  pass_filenames: true
  types: [file]

- id: alloy-format
  name: Format `.alloy` files
  description: Format `.alloy` files using `alloy fmt`. `alloy` must be installed.
  language: system
  files: \.alloy$
  entry: alloy fmt
  args: [--write]
