- id: check-directory-structure
  name: Check directory structure
  description: Check current directory structure.
  entry: check-directory-structure
  language: python
  pass_filenames: false
  types: [python]

- id: source-matching-test
  name: Check Python source has matching test
  description: Check Python source (`src/`) file has matching test file in (`tests/`) directory.
  entry: check-directory-structure
  language: python
  pass_filenames: false
  types: [python]
  args:
    - --source
    - src
    - --target
    - tests
    - --format
    - "test_{file.stem}{file.suffix}"

- id: test-matching-source
  name: Check Python test has matching source
  description: Check Python test (`tests/`) file has matching source file in (`src/`) directory.
  entry: check-directory-structure
  language: python
  pass_filenames: false
  types: [python]
  args:
    - --source
    - tests
    - --target
    - src
    - --eval
    - 'file.stem.removeprefix("test_") + file.suffix'

- id: preferred-suffix
  name: Check filename has preferred suffix
  description: Check filenames to use single preferred suffix over other possible variants.
  entry: preferred-suffix
  language: python
  pass_filenames: true
  types: [file]

- id: alloy-format
  name: Format `.alloy` files
  description: Format `.alloy` files using `alloy fmt`. `alloy` must be installed.
  language: system
  files: \.alloy$
  entry: alloy fmt
  args: [--write]
