default_stages: [pre-commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: ruff-check
        name: Fix using Ruff
        language: system
        types: [python]
        entry: uv run ruff check
        args: [--fix]

      - id: ruff-format
        name: Format using Ruff
        language: system
        types: [python]
        entry: uv run ruff format

      - id: mypy
        name: Type check with Mypy
        language: system
        types: [python]
        entry: uv run mypy
        args: [--show-error-codes, --pretty]

      - id: pytest
        name: Test with pytest
        language: system
        types: [python]
        pass_filenames: false
        entry: uv run pytest

  # To develop local hooks, use `pre-commit try-repo` command.
  # https://pre-commit.com/#developing-hooks-interactively
