- id: check-directory-structure
  name: Check directory structure
  description: Check current directory structure.
  entry: check-directory-structure
  language: python
  pass_filenames: false
  types: [python]
