- id: preferred-suffix
  name: preferred-suffix
  description: Check filenames to use single preferred suffix over other possible variants.
  language: python
  pass_filenames: true
  types: [file]
  entry: preferred-suffix

- id: alloy-format
  name: alloy-format
  description: Format `.alloy` files using `alloy fmt`. `alloy` is required and will not be installed by this hook.
  language: system
  files: \.alloy$
  entry: alloy fmt
  args: [--write]
