target-version = "py311"
select = ["ALL"]
ignore = ["FIX", "TD003", "ANN101", "ANN102", "ANN401", "D100", "D105", "D106"]
line-length = 120

[extend-per-file-ignores]
"__init__.py" = ["D104"]
"tests/*" = ["D", "S101", "PLR2004", "SLF001"]
"scripts/*" = ["INP001", "T201"]
"src/*" = [
  "T201", # Hooks use stdout
]

[pydocstyle]
convention = "google"

[isort]
known-first-party = ["src"]
