[tool.poetry]
name = "pre-commit-hooks"
description = "pre-commit hooks for personal use."
version = "0.1.0"
authors = ["Yuchan Lee <lasuillard@gmail.com>"]
classifiers = ["Private :: Do not Upload"]
packages = [{ include = 'src/**/*.py' }]

[tool.poetry.scripts]
check-directory-structure = "src.check_directory_structure:main"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
coverage = "^7.3.2"
mypy = "^1.7.0"
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
pytest-cov = "^4.1.0"
pytest-env = "^1.1.1"
pytest-sugar = "^0.9.7"
pytest-timeout = "^2.2.0"
pytest-xdist = "^3.4.0"
ruff = "^0.1.5"
pre-commit = "^3.5.0"

[tool.black]
target-version = ["py311"]
line-length = 120
include = '\.pyi?$'
exclude = """
/(
  | .venv
)/
"""
