name: Release

on:
  push:
    tags: [v*]

env:
  UV_FROZEN: 1

# Only one release should run at a time
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: latest
          enable-cache: true

      - name: Install deps
        run: uv sync

      - name: Build package
        run: uv build

      - name: Create release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        with:
          generate_release_notes: false
          files: dist/*

      - name: Upload release distributions
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: release-dists
          path: dist/
